library(terra)
library(readxl)
setwd("D:Personale/Studio/Magistrale/Tesi/zGW_Data/Anomalie_GW_Africa/127973/GWL_anomaly_CSVs")

par(mfrow=c(2,3))
data1<-read.csv("Namibia_Rooibank_gwl_anomaly_wrt_hydraulic_head.csv")
plot(data1$DecYear,data1$GWLanom, type="l")
data2<-read.csv("Niger_Berkiawel_gwl_anomaly_wrt_hydraulic_head.csv")
plot(data2$DecYear,data2$GWLanom, type="l")
data3<-read.csv("Benin_Cococodji_gwl_anomaly_wrt_hydraulic_head.csv")
plot(data3$DecYear,data3$GWLanom, type="l")
data4<-read.csv("Burkina_Faso_Ouagadougou_gwl_anomaly_wrt_hydraulic_head.csv")
plot(data4$DecYear,data4$GWLanom, type="l")
data5<-read.csv("Ghana_Accra_gwl_anomaly_wrt_hydraulic_head.csv")
plot(data5$DecYear,data5$GWLanom, type="l")
data6<-read.csv("Tanzania_Makutapora_gwl_anomaly_wrt_hydraulic_head.csv")
plot(data6$DecYear,data6$GWLanom, type="l")

